#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below :
# -localhost resolves to 127.0.0.2
# -facebook.com resolves to 8.8.8.8.

grep -v -E 'localhost|facebook.com' /etc/hosts > /tmp/hosts
cat /tmp/hosts > /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
